## Copyright (C) 2020 Heherson Domael <h.domael@outlook.com>
## 
## This program is free software: you can redistribute it and/or modify it
## under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
## 
## This program is distributed in the hope that it will be useful, but
## WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
## 
## You should have received a copy of the GNU General Public License
## along with this program.  If not, see
## <https://www.gnu.org/licenses/>.

## -*- texinfo -*- 
## @deftypefn {} {@var{Aroot}, @var{At} =} rootsnonlin_direct (@var{A}, @var{Alow}, @var{Aup})
## Solve for the nearest root of nonlinear equation A on the [Alow, Aup] interval
## using direct or incremental search method.
## @var{Aroot} returns the nearest root of A on [Alow, Aup].
## 
## @var{At} returns the table generated by computing the nearest root of A on [Alow, Aup].
## 
## @end deftypefn

## Author: Heherson Domael <Heherson Domael@LAPTOP-MQALPEGV>
## Created: 2020-03-31

function [Aroot, At] = rootsnonlin_direct (A, Alow, Aup)
  i=1;
  Ad=Aup-Alow;
  while 1
    flow=A(Alow);
    fup=A(Aup);
    if flow*fup>0
      fsign=1;
    else
      fsign=-1;
    endif
    At(i,:)=[i Alow Ad Aup flow fup fsign];
    if abs(flow)<=0.00005
      Aroot=Alow;
      break
    endif
    if abs(fup)<=0.00005
      Aroot=Aup;
      break
    endif
    if fup*flow>=0
      Alow=Aup;
      Aup=Alow+Ad;
    else
      Ad/=2;
      Aup=Alow+Ad;
    endif
    i++;
  endwhile
endfunction
